#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE $CKAN_TEST_DB OWNER "$CKAN_DB_USER" ENCODING 'utf-8';
    CREATE DATABASE $DATASTORE_TEST_DB OWNER "$CKAN_DB_USER" ENCODING 'utf-8';
EOSQL
