#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE ROLE "$MAIN_DB_USER" NOSUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD '$MAIN_DB_PASSWORD';
';
    CREATE DATABASE "$MAIN_DB" OWNER "$MAIN_DB_USER" ENCODING 'utf-8';
EOSQL