name: Test postgres-docker images (PR)

on:
  pull_request:
    branches:
        - main
        - dev

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: postgres-docker
  CONTEXT: .
  BRANCH: ${{ github.head_ref }}
  DOCKERFILE: Dockerfile
  HADOLINT_VERSION: 2.12.0

jobs:
  docker:
    name: runner/test-ckan-pycsw-pr:${{ github.head_ref }}
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout
        uses: actions/checkout@v4

      - name: PostgreSQL build
        uses: docker/build-push-action@v5
        with:
              context: ./postgresql
              file: ./postgresql/${{ env.DOCKERFILE }}
              push: false
              tags: mjanez/postgres-docker-postgresql:test-build-only

      - name: Lint PostgreSQL Dockerfile
        uses: jbergstroem/hadolint-gh-action@v1.12.2
        with:
          dockerfile: ./postgresql/${{ env.DOCKERFILE }}
          version: ${{ env.HADOLINT_VERSION }}
          annotate: true
          error_level: -1

      - name: PgAdmin build
        uses: docker/build-push-action@v5
        with:
              context: ./pgadmin
              file: ./pgadmin/${{ env.DOCKERFILE }}
              push: false
              tags: mjanez/postgres-docker-postgresql:test-build-only

      - name: Lint PgAdmin Dockerfile
        uses: jbergstroem/hadolint-gh-action@v1.12.2
        with:
          dockerfile: ./pgadmin/${{ env.DOCKERFILE }}
          version: ${{ env.HADOLINT_VERSION }}
          annotate: true
          error_level: -1

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Test PgAdmin connection to PostgreSQL
        run: |
          docker run --network container:mjanez/postgres-docker-postgresql:test-build-only postgres:13 psql -h localhost -U postgres -c "SELECT 1"
        env:
          PGPASSWORD: postgres
    